// <auto-generated />
using DynamicPricing.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DynamicPrices.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240114130703_AdaugareTabelProduseElectronice")]
    partial class AdaugareTabelProduseElectronice
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("DynamicPrices.Models.Produse_Electronice", b =>
                {
                    b.Property<int>("IdProdus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<decimal>("CostProducere")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Descriere")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeProdus")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<decimal>("PretRecomandat")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("TipProdus")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("IdProdus");

                    b.ToTable("produse_electronice");
                });
#pragma warning restore 612, 618
        }
    }
}
