// <auto-generated />
using DynamicPricing.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DynamicPrices.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240117182729_AddTabelProduseElectronice")]
    partial class AddTabelProduseElectronice
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("DynamicPrices.Models.Clienti", b =>
                {
                    b.Property<int>("IdClient")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Nume")
                        .IsRequired()
                        .HasColumnType("varchar(60)");

                    b.Property<string>("Prenume")
                        .IsRequired()
                        .HasColumnType("varchar(60)");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("IdClient");

                    b.ToTable("clienti");
                });

            modelBuilder.Entity("DynamicPrices.Models.Produse_Electronice", b =>
                {
                    b.Property<int>("IdProdus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<decimal>("CostProducere")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Descriere")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NumeProdus")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<decimal>("PretRecomandat")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("TipProdus")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("IdProdus");

                    b.ToTable("produse_electronice");
                });
#pragma warning restore 612, 618
        }
    }
}
