// <auto-generated />
using System;
using DynamicPricing.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DynamicPrices.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("DynamicPrices.Models.Preturi_Electronice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DataActualizare")
                        .HasColumnType("date");

                    b.Property<int>("IdProdus")
                        .HasColumnType("int");

                    b.Property<decimal>("PretCurent")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("IdProdus");

                    b.ToTable("preturi_electronice");
                });

            modelBuilder.Entity("DynamicPrices.Models.Produse_Electronice", b =>
                {
                    b.Property<int>("IdProdus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<decimal>("CostProducere")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Descriere")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeProdus")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<decimal>("PretRecomandat")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("TipProdus")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("IdProdus");

                    b.ToTable("produse_electronice");
                });

            modelBuilder.Entity("DynamicPrices.Models.Preturi_Electronice", b =>
                {
                    b.HasOne("DynamicPrices.Models.Produse_Electronice", "Produse_Electronice")
                        .WithMany()
                        .HasForeignKey("IdProdus")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produse_Electronice");
                });
#pragma warning restore 612, 618
        }
    }
}
